#!/usr/bin/env php
<?php

const ROOT_PATH = __DIR__ . '/';

require ROOT_PATH . '/vendor/autoload.php';

$config = (require(ROOT_PATH . 'config/cli.php')) + (require(ROOT_PATH . 'config/params.php'));

core\App::init($config, 'Cli');